pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = 'github-creds'
        GIT_BRANCH = 'main'  
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${GIT_BRANCH}", credentialsId: "${GIT_CREDENTIALS_ID}", url: 'https://github.com/MathiasDigit/messaging_app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip3 install -r messaging_app/requirements.txt  # ✅ Chemin complet
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }

        stage('Archive Results') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
