#!/bin/bash

echo ""Starting Minikube cluster...""
minikube start 

echo -e "\nVerifying cluster info..."
kubectl cluster-info

echo -e "nListing all pods in all namespaces..."
kubectl get pods --all-namespaces
